// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOB1ihUpHOZQ_Spo7ZuglDkaX__bAZwug',
    appId: '1:112848755825:web:b102dd5184d05464ebcfd0',
    messagingSenderId: '112848755825',
    projectId: 'wordcreate-237c7',
    authDomain: 'wordcreate-237c7.firebaseapp.com',
    storageBucket: 'wordcreate-237c7.firebasestorage.app',
    measurementId: 'G-E1VWGZJ92S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8HwPYV7WQ9nbW9iMwAX95YxeDbIC-0Tk',
    appId: '1:112848755825:android:ec2f496b8c21d283ebcfd0',
    messagingSenderId: '112848755825',
    projectId: 'wordcreate-237c7',
    storageBucket: 'wordcreate-237c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFIzOUpVxYeSX-nqchdDjJMiCWP7Hbe4',
    appId: '1:112848755825:ios:cafcf736f28e7da5ebcfd0',
    messagingSenderId: '112848755825',
    projectId: 'wordcreate-237c7',
    storageBucket: 'wordcreate-237c7.firebasestorage.app',
    iosBundleId: 'com.example.wordcreate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvFIzOUpVxYeSX-nqchdDjJMiCWP7Hbe4',
    appId: '1:112848755825:ios:cafcf736f28e7da5ebcfd0',
    messagingSenderId: '112848755825',
    projectId: 'wordcreate-237c7',
    storageBucket: 'wordcreate-237c7.firebasestorage.app',
    iosBundleId: 'com.example.wordcreate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOB1ihUpHOZQ_Spo7ZuglDkaX__bAZwug',
    appId: '1:112848755825:web:e00e9dac1405d6deebcfd0',
    messagingSenderId: '112848755825',
    projectId: 'wordcreate-237c7',
    authDomain: 'wordcreate-237c7.firebaseapp.com',
    storageBucket: 'wordcreate-237c7.firebasestorage.app',
    measurementId: 'G-N3YVD94RWB',
  );
}
